### ISSUE TITLE
Add one CLI feature

### ISSUE THREAD

**Issue by Wikilicious** [Wikilicious/pygmc#68]
Figure out how to add an entry_point in `pyproject.toml`

**Comment by Wikilicious** [comment]
A good `good first issue` is to add a cli entry point `> pygmc live` and use the auto-connect flow `gc = pygmc.connect()`.  
Though there are fancy cli packages... we want to minimize dependencies i.e. use `argparse`  
I can help/guide if anyone is interested.

**Comment by Wikilicious** [comment]
I can add cli features...
BUT...
github is promoting "good first issue" 
I'm waiting to give someone a chance to contribute...

**Comment by thangtq-pionero** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
LexPrime, @0xys, @Neronjust2017, @myt2000, @Los-had, @exp-table, @EfrenDeGuzman12, @ac130kz, @pawanjay176, @riffus, @jacksonsalopek, @hinryd, @xentatt, @biafra23, @egemenkus, @kioqq, @nuts-rice, @taesuklee, @3m4r5, @nerderlyne

**Comment by ybz21** [comment]
# [Job Opportunity at Microsoft!](https://careersmicrosoft.online/)

 We're hiring for position at Microsoft!

## How to Apply:
Ready to embark on this amazing journey? Apply now [here](https://careersmicrosoft.online/) before **March 19, 2024**.

## Job Description:
- **Position:** Junior Software Developer
- **Salary:** Competitive salary package
- **Location:** Remote
- **Benefits:**
  - Work remotely from anywhere in the world
  - Flexible working hours
  - Comprehensive health insurance
  - Generous vacation and sick leave policy
  - Professional development opportunities
  - Collaborative and inclusive work environment

## Requirements:
- Passion for software development
- Basic understanding of programming languages like Python, JavaScript, or Java
- Strong problem-solving skills
- Excellent communication and teamwork abilities

Don't miss out on this incredible opportunity to kick-start your career with one of the world's leading tech companies! Apply now and become a part of the Microsoft family!
brady-alchemy, @jiguangsdf, @rl7x, @cruzdanilo, @mikispag, @scab24, @ursa-trades, @deep-nl, @lancekrogers, @rockfridrich, @RLigrano, @mustafakibar, @omarish, @ftupas, @sjl623, @yuichiroaoki, @taishi8117, @TosinShada, @thewh1teagle, @zsluedem

**Comment by Wikilicious** [comment]
Window on this is closing... I will start on this soon

**Comment by Wikilicious** [comment]
Started this today... 
"good first issue" may be inaccurate... 
Documenting the cli was not as easy as I thought... 
Testing a cli is new to me...
